### ISSUE TITLE
403s on downgraded APK

### ISSUE THREAD

**Issue by ASleepyCat** [arsenicx6/Archive-Reader-Downgrade#1]
Unable to login or search.

On a side note, it might not be wise to publish the decompiled code. It would be safer to make and publish patches to get around the subscription limits instead.

**Comment by lillifer** [comment]
The 403 error happens on the most recent version too, so it's unlikely the older version of the app is at fault

**Comment by Crusader2113** [comment]
![Screenshot_20231222-101656](https://github.com/arsenicx6/Archive-Reader-Downgrade/assets/154613393/6b86389c-a5fd-442d-b0a7-ae84e0b36bea)
It goes farther than that, the app doesn't seem to be able to access the AO3 archive itself, it doesn't detect any works, all the tags have 0 related works.

**Comment by arsenicx6** [comment]
If i had to make a wild guess, I think that apps like this have access to AO3 via some sort of API or just general backend service. 
And considering how the dev rolled this update out, the stink it caused, and [AO3's recent vague tweet](https://twitter.com/AO3_Status/status/1737284936967541023) about not having an app, I think what has happened is that they pulled the plug on the dev's access. The dev is probably facing a few emails or legal threats from AO3 at the moment. 

It sucks that, if this is what's happening, that it ruins the old versions of the app too. But it's nice to know that, if that's what is happening, something is being done.

This is also why I'm working to try and rip the app's source code, because then all it would take is a simple API token swap (or something to that effect).

Not gonna close the issue because I think as the situation develops we might get more info.

**Comment by arsenicx6** [comment]
On the topic of making patches to subvert the update:

Unfortunately, I don't think I have the skill for that. If someone else wants to try and contribute their knowledge to this project to make that happen but I still think that requires the source code anyways.

And, frankly, fuck the dev. I just kinda wanna put the source code out there as a big middle finger.

**Comment by GeekTheSiren** [comment]
Yeah, afaik, the 403s are from AO3, not the app. Don't think there's any way to subvert this without doing something none of us know how to do lol. Looks like we're just gonna have to deal.

**Comment by GeekTheSiren** [comment]
ACTUALLY, given how the official unofficial app seems to have been able to subvert this, you might be able to do some finagling and compare where they both get the fics from. Or for that matter, if you can get the current version of the app and substitute the paywalled bits with the bits from this downgraded version- but nothing else- you'd get an up-to-date app without a paywall. But, I have no idea how to do any of that, so I'm assuming you know how that stuff works.

**Comment by lillifer** [comment]
I would wait until things settle before trying to fix it. I feel like AO3 will probably block the app again, making the fix on the original app useless

**Comment by mdrakea** [comment]
> If i had to make a wild guess, I think that apps like this have access to AO3 via some sort of API or just general backend service.

No-- otwarchive doesn't have an API, and apps like this one work via just parsing the raw website itself

Also, as a warning to anyone else who wants to try and decompile the app: be warned it's written in Flutter which gets compiled to native code, so you're going to have a far harder time interpreding it (i tried once myself to have better insight as to how parsing apis like this work for my own (open source/Not Monetizing Other Peoples Work project) and it's honestly not worth it because of how annoying Dart is to work with)

**Comment by mdrakea** [comment]
Although, because of the aforementioned difficulty, I don't... actually know how the app works? For all I know it could use a custom API that parses an otwarchive instance serverside and sends its results to the app more programmatically to simplify app development (though I don't exactly find that likely but it could be the case)

**Comment by ASleepyCat** [comment]
> Although, because of the aforementioned difficulty, I don't... actually know how the app works? For all I know it could use a custom API that parses an otwarchive instance serverside and sends its results to the app more programmatically to simplify app development (though I don't exactly find that likely but it could be the case)

Based off of the network traffic it just connects to ao3.org (via Cloudflare) and `api.shorebird.dev`, which I assume is how the dev is able to push live update notifications/messages on the sidebar.

I wonder how AO3 is able to block the app specifically then, considering all the 403s and that going to the website on my phone's browser works fine. I guess there's some Cloudflare magic going on?

**Comment by mdrakea** [comment]
> I guess there's some Cloudflare magic going on?

Alternatively, if the dev was nice and set a user-agent that indicates what the app was, they could just be straight up blocking the app's user-agent lol

**Comment by lillifer** [comment]
Hey, it's working! I tried it on a whim today and was able to sign in and search for stuff.

**Comment by ASleepyCat** [comment]
Reinstalled 1.5.2, can confirm logging in and and search works. Also can read stuff, closing.
